version: "3.8"

services:
    social-media:
        build:
            context: .
        ports:
            - 3000:3000
        environment:
            - SERVER_PORT=8000
            - CONNECTIONSTRING=mongodb://mongo:27017/notes
        env_file:
            - .env
